name: Pulumi
on:
  pull_request: {}
  push:
    branches:
      - '!master'
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Preview changes
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: mcapala/mcapala-domain/dns-py
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}