name: Pulumi
on:
  push:
    branches:
      - '**' #TODO: Change to master
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Applying changes
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: mcapala/mcapala-domain/dns-py
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}